name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Build
      working-directory: ruby
      run: gem install minitest
    - name: Run tests
      working-directory: ruby
      run: ruby -r minitest/pride **/*test.rb
